<?php

namespace AppBundle\Repository;

/**
 * AdressAptekiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdressAptekiRepository extends \Doctrine\ORM\EntityRepository
{
}
