<?php

namespace AppBundle\Repository;

/**
 * AptekaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AptekaRepository extends \Doctrine\ORM\EntityRepository
{
}
