<?php

namespace AppBundle\Repository;

/**
 * ChorobaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChorobaRepository extends \Doctrine\ORM\EntityRepository
{
}
