<?php

namespace AppBundle\Repository;

/**
 * DiagnozaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiagnozaRepository extends \Doctrine\ORM\EntityRepository
{
}
