<?php

namespace AppBundle\Repository;

/**
 * GodzinyPrzyjecRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GodzinyPrzyjecRepository extends \Doctrine\ORM\EntityRepository
{
}
