<?php

namespace AppBundle\Repository;

/**
 * GodzinyOtwarciaAptekiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GodzinyOtwarciaAptekiRepository extends \Doctrine\ORM\EntityRepository
{
}
