<?php

namespace AppBundle\Repository;

/**
 * LekRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LekRepository extends \Doctrine\ORM\EntityRepository
{
}
