<?php

namespace AppBundle\Repository;

/**
 * PacjentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PacjentRepository extends \Doctrine\ORM\EntityRepository
{
}
