<?php

namespace AppBundle\Repository;

/**
 * ReceptaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReceptaRepository extends \Doctrine\ORM\EntityRepository
{
}
