<?php

namespace AppBundle\Repository;

/**
 * SpecjalizacjaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecjalizacjaRepository extends \Doctrine\ORM\EntityRepository
{
}
