<?php

namespace AppBundle\Repository;

/**
 * StanMagazynuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StanMagazynuRepository extends \Doctrine\ORM\EntityRepository
{
}
