<?php

namespace AppBundle\Repository;

/**
 * TydzienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TydzienRepository extends \Doctrine\ORM\EntityRepository
{
}
