<?php

namespace AppBundle\Repository;

/**
 * WizytaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WizytaRepository extends \Doctrine\ORM\EntityRepository
{
}
