# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
              users:
                    lekarz:
                        password: lek
                        roles: 'ROLE_LEKARZ'
                    aptekarz:
                        password: apt
                        roles: 'ROLE_APTEKARZ'
                    pacjent:
                        password: pcj
                        roles: 'ROLE_PACJENT'
                    admin:
                        password: kitten
                        roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
            # activate different ways to authenticate

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/lekarz, roles: ROLE_ADMIN, ROLE_LEKARZ}
        - { path: ^/aptekarz, roles: ROLE_ADMIN, ROLE_APTEKARZ}
        - { path: ^/pacjent, roles: ROLE_ADMIN, ROLE_PACJENT}
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
